 pipeline {
    agent any
    stages {
        stage('Stage 0: Checkout Proyecto GIT'){
            steps{
                    git branch: 'develop',
                    credentialsId: 'codecommit-user-at-222923733616',
                    url: 'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/todo-list-aws'
            }
        }
        
        stage('Stage 1: Setup'){
            steps{
                    sh 'bash pipeline/PIPELINE-FULL-STAGING/1-setup.sh'  
            }
        }
        stage('Stage 2: Pruebas'){
            steps{
                    sh 'bash pipeline/PIPELINE-FULL-STAGING/2-testing.sh'
            }
        }
        stage('Stage 3: Construccion'){
            steps{
                    sh 'bash pipeline/PIPELINE-FULL-STAGING/3-package.sh'
           }
        }
        stage('Stage 4: Despliegue'){
            steps{
                    sh 'bash pipeline/PIPELINE-FULL-STAGING/4-deploy.sh'
            }
        }
        stage('Stage 5: Pruebas de Integracion'){
            steps{
                sh 'bash pipeline/PIPELINE-FULL-STAGING/5-integration.sh'
            }
        }
        stage('Stage 6: Limpieza'){
            steps{
              deleteDir()
            }
        }
    }
    post {
        always{
            //sh 'docker rm -f dynamodb'
            sh '''#!/bin/bash
                 docker ps -a -q | xargs docker rm -f -v
                 docker volume prune -f
            '''
        }
        failure {
            echo 'Malas noticias!!'
            deleteDir()
        }
    }
}
